apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: connect-app
  description: API TEST
  tags:
  - nestjs
  - internal-api
  links:
  - url: http://127.0.0.1:3000/
    title: Healthcheck (dev)
    icon: favorite
  annotations:
    github.com/project-slug: https://github.com/HUIKUB/backstate-nestjs-demo
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-id: connect-app
spec:
  type: service
  lifecycle: development
  owner: HUI
  system: core-platform
