apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: nestjs
  description: nestjs for test
  annotations:
    backstage.io/source-location: url:https://github.com/HUIKUB/backstate-nestjs-demo
    backstage.io/kubernetes-id: demo
    backstage.io/kubernetes-label-selector: backstage.io/kubernetes-id=demo-nestjs
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: HUIKUB/backstate-nestjs-demo
  tags:
  - nestjs
  links:
  - url: https://nestjs.com
    title: Nestjs
    type: website
spec:
  type: service
  lifecycle: experimental
  owner: HUIKUB
  consumesApis:
  - huikub-nginx-api
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: HUIKUB-nginx
  description: nginx on kind
  annotations:
    backstage.io/source-location: url:https://github.com/HUIKUB/backstate-nestjs-demo
    backstage.io/kubernetes-id: demo
    backstage.io/kubernetes-label-selector: backstage.io/kubernetes-id=demo-nginx
    backstage.io/techdocs-ref: url:https://github.com/HUIKUB/backstate-nestjs-demo/tree/main
    prometheus.io/service-name: staging
    prometheus.io/rule: up|job
    prometheus.io/alert: all
    grafana/dashboard-selector: 'tag=test'
    grafana/alert-label-selector: 'service=huikub'
    grafana/overview-dashboard: 'd/nginx_uid/nginx-overview?orgId=1&var-service=huikub'
    github.com/project-slug: HUIKUB/backstate-nestjs-demo
  tags:
  - nginx
  links:
  - url: https://nginx.org
    title: NGINX Official Website
    icon: nginx
    type: website
spec:
  type: service
  lifecycle: experimental
  owner: HUIKUB
  providesApis:
  - huikub-nginx-api
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: huikub-nginx-api
  description: Simple nginx demo API
spec:
  type: openapi
  lifecycle: experimental
  owner: team-huikub
  definition: |
    openapi: 3.0.0
    info:
      title: HUIKUB Nginx Demo API
      version: 1.0.0
    servers:
      - url: https://api.huikub.local
    paths:
      /health:
        get:
          summary: Health check
          operationId: getHealth
          responses:
            '200':
              description: OK
      /nginx/info:
        get:
          summary: Get nginx info
          operationId: getNginxInfo
          responses:
            '200':
              description: nginx info returned
