apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: nestjs
  description: nestjs for test
  annotations:
    github.com/project-slug: HUIKUB/backstate-nestjs-demo
    backstage.io/kubernetes-id: demo
    backstage.io/kubernetes-label-selector: backstage.io/kubernetes-id=demo-nestjs
    backstage.io/techdocs-ref: dir:.
  tags:
  - nestjs
  links:
  - url: https://nestjs.com
    title: Nestjs
    type: website
spec:
  type: service
  lifecycle: experimental
  owner: HUIKUB
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: HUIKUB-nginx
  description: nginx on kind
  annotations:
    github.com/project-slug: HUIKUB/backstate-demo
    backstage.io/kubernetes-id: demo
    backstage.io/kubernetes-label-selector: backstage.io/kubernetes-id=demo-nginx
    backstage.io/techdocs-ref: url:https://github.com/HUIKUB/backstate-nestjs-demo/tree/main
  tags:
  - nginx
  links:
  - url: https://nginx.org
    title: NGINX Official Website
    icon: nginx
    type: website
spec:
  type: service
  lifecycle: experimental
  owner: HUIKUB
  providesApis:
  - huikub-user-api
