---
apiVersion: v1
kind: Namespace
metadata:
  name: backstage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: backstage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      automountServiceAccountToken: false
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:8.14.0
        ports:
        - containerPort: 9200
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
            ephemeral-storage: "1Gi"
          limits:
            memory: "2Gi"
            cpu: "1"
            ephemeral-storage: "5Gi"
        env:
        - name: discovery.type
          value: single-node
        - name: xpack.security.enabled
          value: "false"
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: backstage
spec:
  type: NodePort
  selector:
    app: elasticsearch
  ports:
  - protocol: TCP
    port: 9200
    targetPort: 9200
    nodePort: 30092
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch-exporter
  namespace: backstage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch-exporter
  template:
    metadata:
      labels:
        app: elasticsearch-exporter
    spec:
      automountServiceAccountToken: false
      containers:
      - name: exporter
        image: quay.io/prometheuscommunity/elasticsearch-exporter:v1.7.0
        ports:
        - containerPort: 9114
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
            ephemeral-storage: "128Mi"
          limits:
            memory: "256Mi"
            cpu: "250m"
        env:
        - name: ES_URI
          value: http://elasticsearch:9200
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-exporter
  namespace: backstage
spec:
  type: NodePort
  selector:
    app: elasticsearch-exporter
  ports:
  - protocol: TCP
    port: 9114
    targetPort: 9114
    nodePort: 30114
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: backstage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      automountServiceAccountToken: false
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:8.14.0
        ports:
        - containerPort: 5601
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
            ephemeral-storage: "256Mi"
          limits:
            memory: "512Mi"
            cpu: "500m"
            ephemeral-storage: "1Gi"
        env:
        - name: ELASTICSEARCH_HOSTS
          value: http://elasticsearch:9200
        - name: ELASTICSEARCH_USERNAME
          value: "elastic"
        - name: ELASTICSEARCH_PASSWORD
          value: "changeme"
        - name: SERVER_NAME
          value: "kibana"
        - name: xpack.security.enabled
          value: "false"
        - name: xpack.encryptedSavedObjects.encryptionKey
          value: "something_at_least_32_characters"
---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: backstage
spec:
  type: NodePort
  selector:
    app: kibana
  ports:
  - protocol: TCP
    port: 5601
    targetPort: 5601
    nodePort: 30056
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: backstage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      automountServiceAccountToken: false
      containers:
      - name: prometheus
        image: prom/prometheus:v2.52.0
        ports:
        - containerPort: 9090
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
            ephemeral-storage: "256Mi"
          limits:
            memory: "512Mi"
            cpu: "500m"
            ephemeral-storage: "1Gi"
        volumeMounts:
        - name: prometheus-config
          mountPath: /etc/prometheus
      volumes:
      - name: prometheus-config
        configMap:
          name: prometheus-config
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: backstage
spec:
  type: NodePort
  selector:
    app: prometheus
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 9090
    nodePort: 30090
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: backstage
  labels:
    app: prometheus
  annotations:
    prometheus.io/scrape: "true"
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'elasticsearch'
        static_configs:
          - targets: ['elasticsearch-exporter:9114']
