# demo-nginx.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-nginx
  namespace: default
  labels:
    app.kubernetes.io/name: demo-nginx
    backstage.io/kubernetes-id: demo-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: demo-nginx
      backstage.io/kubernetes-id: demo-nginx
  consumesApis:
  - huikub-user-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: demo-nginx
        backstage.io/kubernetes-id: demo-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.25-alpine
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: demo-svc
  namespace: default
  labels:
    app.kubernetes.io/name: demo-nginx
    backstage.io/kubernetes-id: demo-nginx
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: demo-nginx
    backstage.io/kubernetes-id: demo-nginx
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
